/*
 * Copyright 2026 Spectrayan
 *
 * Licensed under the Business Source License 1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://github.com/spectrayan/spector/blob/main/spector-memory/LICENSE
 *
 * Change Date: May 27, 2030
 * Change License: Apache License, Version 2.0
 */
package com.spectrayan.spector.memory;

import java.time.Duration;

/**
 * Report generated by the reflection (sleep consolidation) process.
 *
 * @param consolidatedCount number of episodic clusters promoted to Semantic tier
 * @param tombstonedCount   number of memories tombstoned during Deep Sleep pruning
 * @param compactedPartitions number of partitions that were rebuilt after tombstone threshold
 * @param duration          total time taken for the reflection cycle
 */
public record ReflectReport(
        int consolidatedCount,
        int tombstonedCount,
        int compactedPartitions,
        Duration duration
) {

    /**
     * Returns true if any work was done during this reflection cycle.
     */
    public boolean hadActivity() {
        return consolidatedCount > 0 || tombstonedCount > 0 || compactedPartitions > 0;
    }

    /**
     * Empty report — no work done.
     */
    public static final ReflectReport EMPTY = new ReflectReport(0, 0, 0, Duration.ZERO);
}
